import { useEffect, useRef, useState } from 'react'
import Kit from './lib/kit.js'
import { enterDemo, request, type Session } from './lib/api'
import RoleControl from './components/RoleDrawer'

type Context={class_name:string;level_label:string|null;teacher_display_name:string;teacher_introduction:string|null}
type Summary={id:string;state:string;delivered_at:string;help_requested:boolean;title:string}
type Detail={id:string;state:string;help_requested:boolean;completed_step_ids:string[];answers:Record<string,string>;packet:{title:string;steps:{id:string;title:string;blocks:{text:string;citations:{segment_id:string;page_or_section:string}[]}[]}[];questions:{id:string;prompt:string;options:Record<string,string>}[]}}

export default function Student(){
  const [session,setSession]=useState<Session|null>(null),[context,setContext]=useState<Context|null>(null),[items,setItems]=useState<Summary[]>([]),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState('')
  const themeSlot=useRef<HTMLSpanElement>(null)
  useEffect(()=>{void enterDemo('student').then(async s=>{setSession(s);const [c,a]=await Promise.all([request<Context>('/student/context'),request<Summary[]>('/student/assignments')]);setContext(c);setItems(a)}).catch(e=>setError(e.message))},[])
  useEffect(()=>{if(session)Kit.themeToggle(()=>{},themeSlot.current)},[session])
  async function open(id:string){try{const d=await request<Detail>(`/student/assignments/${id}`);setDetail(d);const first=d.packet.steps[0]?.id;if(first)await request(`/student/assignments/${id}/progress`,{method:'POST',body:JSON.stringify({step_id:first,event:'opened'})})}catch(e){setError(e instanceof Error?e.message:'Could not open assignment')}}
  if(error)return <main className="page narrow"><section className="panel"><h2>Could not open learner view</h2><p className="neg">{error}</p></section></main>
  if(!session||!context)return <main className="page narrow"><p className="eyebrow">Opening learner assignments…</p></main>
  return <><header className="topbar"><div className="brand"><b>CLASS CATCH-UP</b><span>LEARNER VIEW</span></div><nav className="nav"><button className={!detail?'on':''} onClick={()=>setDetail(null)}>Assignments</button></nav><div className="spacer"/><span className="hdr-meta"><b>{context.class_name}</b> · {context.level_label} · {session.display_name}</span><span ref={themeSlot}/><RoleControl role="student"/></header>{detail?<Packet detail={detail} refresh={()=>open(detail.id)} back={()=>setDetail(null)}/>:<main className="page narrow"><section className="intro-card panel"><p className="eyebrow">{context.class_name} · {context.level_label}</p><h1 className="display-sm">Hello from {context.teacher_display_name}</h1><p className="dim">{context.teacher_introduction}</p></section><div className="assign-list">{!items.length&&<p className="dim">No published assignments yet.</p>}{items.map(a=><button className="assign-card panel" key={a.id} onClick={()=>open(a.id)}><div className="ac-top"><b>{a.title}</b><span className={'tag '+(a.state==='submitted'?'t-ok':'t-warn')}>{a.state.replaceAll('_',' ')}</span></div><span className="dim small">Published {new Date(a.delivered_at).toLocaleDateString()}</span>{a.help_requested&&<span className="tag t-warn">Help requested</span>}</button>)}</div></main>}</>
}

function Packet({detail,refresh,back}:{detail:Detail;refresh:()=>void;back:()=>void}){
  const [answers,setAnswers]=useState(detail.answers),[results,setResults]=useState<Record<string,boolean>>({}),[help,setHelp]=useState(''),[notice,setNotice]=useState('')
  const done=new Set(detail.completed_step_ids)
  async function complete(stepId:string){try{await request(`/student/assignments/${detail.id}/progress`,{method:'POST',body:JSON.stringify({step_id:stepId,event:'completed'})});refresh()}catch(e){setNotice(e instanceof Error?e.message:'Could not save progress')}}
  async function answer(qid:string){try{const r=await request<{correctness:boolean}>(`/student/assignments/${detail.id}/attempts`,{method:'POST',body:JSON.stringify({question_id:qid,answer:answers[qid]})});setResults(v=>({...v,[qid]:r.correctness}));refresh()}catch(e){setNotice(e instanceof Error?e.message:'Could not check answer')}}
  async function submit(){const step=detail.packet.steps[0]?.id;if(!step)return;try{await request(`/student/assignments/${detail.id}/progress`,{method:'POST',body:JSON.stringify({step_id:step,event:'submitted'})});setNotice('Your catch-up work was submitted.');refresh()}catch(e){setNotice(e instanceof Error?e.message:'Could not submit')}}
  async function sendHelp(){const step=detail.packet.steps[0]?.id;if(!step||!help.trim())return;try{await request(`/student/assignments/${detail.id}/help`,{method:'POST',body:JSON.stringify({step_id:step,message:help.trim()})});setNotice('Your teacher can now see this request.');setHelp('')}catch(e){setNotice(e instanceof Error?e.message:'Could not request help')}}
  const allDone=detail.packet.steps.every(s=>done.has(s.id))&&detail.packet.questions.every(q=>detail.answers[q.id]||answers[q.id])
  return <main className="page narrow"><button className="btn back" onClick={back}>← All assignments</button><section className="panel pkt"><div className="panel-head"><h2>{detail.packet.title}</h2><span className="tag">{detail.state}</span></div><div className="panel-body">{notice&&<p className="note">{notice}</p>}<p className="eyebrow">Steps · read, then mark complete</p>{detail.packet.steps.map((s,i)=><div className={'s-step'+(done.has(s.id)?' done':'')} key={s.id}><div className="step-head"><span className="ix">{String(i+1).padStart(2,'0')}</span><b>{s.title}</b><span className="spacer"/><button className={'btn'+(done.has(s.id)?' primary':'')} onClick={()=>complete(s.id)} disabled={done.has(s.id)}>{done.has(s.id)?'Completed ✓':'Mark complete'}</button></div>{s.blocks.map((b,j)=><div key={j}><blockquote>{b.text}</blockquote><span className="cite">{b.citations.map(c=>c.page_or_section).join(', ')}</span></div>)}</div>)}<p className="eyebrow">Questions</p>{detail.packet.questions.map((q,i)=><div className="s-q" key={q.id}><b>Q{i+1}. {q.prompt}</b><div className="s-opts">{Object.entries(q.options).map(([key,label])=><label className={'s-opt'+(answers[q.id]===key?' on':'')} key={key}><input type="radio" name={q.id} checked={answers[q.id]===key} onChange={()=>setAnswers(v=>({...v,[q.id]:key}))}/><span>{label}</span></label>)}</div><button className="btn" disabled={!answers[q.id]} onClick={()=>answer(q.id)}>Check answer</button>{q.id in results&&<p className={'verdict '+(results[q.id]?'pos':'neg')}>{results[q.id]?'Correct — well done.':'Not quite. Re-read the cited step and try again.'}</p>}</div>)}<div className="s-foot"><button className="btn primary big" disabled={!allDone||detail.state==='submitted'} onClick={submit}>Submit my catch-up work</button><div className="help-box"><label htmlFor="help">Ask your teacher for help</label><textarea id="help" value={help} onChange={e=>setHelp(e.target.value)}/><button className="btn" disabled={!help.trim()} onClick={sendHelp}>Send help request</button></div></div></div></section></main>
}
