import { useEffect, useRef, useState } from 'react'
import Kit from './lib/kit.js'
import { enterDemo, request, type Session } from './lib/api'
import RoleControl from './components/RoleDrawer'

type Context={class_name:string;level_label:string|null;teacher_display_name:string;teacher_introduction:string|null}
type Summary={id:string;state:string;delivered_at:string;help_requested:boolean;title:string}
type Detail={id:string;state:string;help_requested:boolean;completed_step_ids:string[];answers:Record<string,string>;packet:{title:string;steps:{id:string;title:string;blocks:{text:string;citations:{segment_id:string;page_or_section:string}[]}[]}[];questions:{id:string;prompt:string;options:Record<string,string>}[]}}
type LessonMode='watch'|'visual'|'read'

export default function Student(){
  const [session,setSession]=useState<Session|null>(null),[context,setContext]=useState<Context|null>(null),[items,setItems]=useState<Summary[]>([]),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState('')
  const themeSlot=useRef<HTMLSpanElement>(null)
  useEffect(()=>{void enterDemo('student').then(async s=>{setSession(s);const [c,a]=await Promise.all([request<Context>('/student/context'),request<Summary[]>('/student/assignments')]);setContext(c);setItems(a)}).catch(e=>setError(e.message))},[])
  useEffect(()=>{if(session)Kit.themeToggle(()=>{},themeSlot.current)},[session])
  async function open(id:string){try{const d=await request<Detail>(`/student/assignments/${id}`);setDetail(d);const first=d.packet.steps[0]?.id;if(first)await request(`/student/assignments/${id}/progress`,{method:'POST',body:JSON.stringify({step_id:first,event:'opened'})})}catch(e){setError(e instanceof Error?e.message:'Could not open assignment')}}
  if(error)return <main className="page narrow"><section className="panel"><h2>Could not open learner view</h2><p className="neg">{error}</p></section></main>
  if(!session||!context)return <main className="page narrow"><p className="eyebrow">Opening learner assignments…</p></main>
  return <><header className="topbar"><div className="brand"><b>CLASS CATCH-UP</b><span>LEARNER VIEW</span></div><nav className="nav"><button className={!detail?'on':''} onClick={()=>setDetail(null)}>Assignments</button></nav><div className="spacer"/><span className="hdr-meta"><b>{context.class_name}</b> · {context.level_label} · {session.display_name}</span><span ref={themeSlot}/><RoleControl role="student"/></header>{detail?<Packet detail={detail} refresh={()=>open(detail.id)} back={()=>setDetail(null)}/>:<main className="page narrow"><section className="intro-card panel"><p className="eyebrow">{context.class_name} · {context.level_label}</p><h1 className="display-sm">Hello from {context.teacher_display_name}</h1><p className="dim">{context.teacher_introduction}</p></section><div className="assign-list">{!items.length&&<p className="dim">No published assignments yet.</p>}{items.map(a=><button className="assign-card panel" key={a.id} onClick={()=>open(a.id)}><div className="ac-top"><b>{a.title}</b><span className={'tag '+(a.state==='submitted'?'t-ok':'t-warn')}>{a.state.replaceAll('_',' ')}</span></div><span className="dim small">Published {new Date(a.delivered_at).toLocaleDateString()}</span>{a.help_requested&&<span className="tag t-warn">Help requested</span>}</button>)}</div></main>}</>
}

function Packet({detail,refresh,back}:{detail:Detail;refresh:()=>void;back:()=>void}){
  const [answers,setAnswers]=useState(detail.answers),[results,setResults]=useState<Record<string,boolean>>({}),[help,setHelp]=useState(''),[notice,setNotice]=useState('')
  const done=new Set(detail.completed_step_ids)
  async function complete(stepId:string){try{await request(`/student/assignments/${detail.id}/progress`,{method:'POST',body:JSON.stringify({step_id:stepId,event:'completed'})});refresh()}catch(e){setNotice(e instanceof Error?e.message:'Could not save progress')}}
  async function answer(qid:string){try{const r=await request<{correctness:boolean}>(`/student/assignments/${detail.id}/attempts`,{method:'POST',body:JSON.stringify({question_id:qid,answer:answers[qid]})});setResults(v=>({...v,[qid]:r.correctness}));refresh()}catch(e){setNotice(e instanceof Error?e.message:'Could not check answer')}}
  async function submit(){const step=detail.packet.steps[0]?.id;if(!step)return;try{await request(`/student/assignments/${detail.id}/progress`,{method:'POST',body:JSON.stringify({step_id:step,event:'submitted'})});setNotice('Your catch-up work was submitted.');refresh()}catch(e){setNotice(e instanceof Error?e.message:'Could not submit')}}
  async function sendHelp(){const step=detail.packet.steps[0]?.id;if(!step||!help.trim())return;try{await request(`/student/assignments/${detail.id}/help`,{method:'POST',body:JSON.stringify({step_id:step,message:help.trim()})});setNotice('Your teacher can now see this request.');setHelp('')}catch(e){setNotice(e instanceof Error?e.message:'Could not request help')}}
  const allDone=detail.packet.steps.every(s=>done.has(s.id))&&detail.packet.questions.every(q=>detail.answers[q.id]||answers[q.id])
  return <main className="page narrow"><button className="btn back" onClick={back}>← All assignments</button><section className="panel pkt"><div className="panel-head"><h2>{detail.packet.title}</h2><span className="tag">{detail.state}</span></div><div className="panel-body">{notice&&<p className="note" aria-live="polite">{notice}</p>}<LessonFormats packet={detail.packet} done={done} complete={complete}/><p className="eyebrow">Check what you understood</p>{detail.packet.questions.map((q,i)=><div className="s-q" key={q.id}><b>Q{i+1}. {q.prompt}</b><div className="s-opts">{Object.entries(q.options).map(([key,label])=><label className={'s-opt'+(answers[q.id]===key?' on':'')} key={key}><input type="radio" name={q.id} checked={answers[q.id]===key} onChange={()=>setAnswers(v=>({...v,[q.id]:key}))}/><span>{label}</span></label>)}</div><button className="btn" disabled={!answers[q.id]} onClick={()=>answer(q.id)}>Check answer</button>{q.id in results&&<p className={'verdict '+(results[q.id]?'pos':'neg')}>{results[q.id]?'Correct — well done.':'Not quite. Re-read the cited step and try again.'}</p>}</div>)}<div className="s-foot"><button className="btn primary big" disabled={!allDone||detail.state==='submitted'} onClick={submit}>Submit my catch-up work</button><div className="help-box"><label htmlFor="help">Ask your teacher for help</label><textarea id="help" value={help} onChange={e=>setHelp(e.target.value)}/><button className="btn" disabled={!help.trim()} onClick={sendHelp}>Send help request</button></div></div></div></section></main>
}

function LessonFormats({packet,done,complete}:{packet:Detail['packet'];done:Set<string>;complete:(stepId:string)=>Promise<void>}){
  const [mode,setMode]=useState<LessonMode>('watch'),[scene,setScene]=useState(0),[playing,setPlaying]=useState(false)
  const steps=packet.steps, active=steps[scene]??steps[0]
  useEffect(()=>{
    if(!playing||mode!=='watch'||!steps.length)return
    const timer=window.setTimeout(()=>{if(scene<steps.length-1)setScene(value=>value+1);else setPlaying(false)},5200)
    return()=>window.clearTimeout(timer)
  },[playing,mode,scene,steps.length])
  function choose(next:LessonMode){setMode(next);setPlaying(false)}
  function restart(){setScene(0);setPlaying(true)}
  const positions=[[90,80],[510,80],[90,290],[510,290]]
  return <section className="lesson-formats" aria-labelledby="lesson-format-title"><div className="lesson-intro"><div><p className="eyebrow">Your missed lesson, three ways</p><h3 id="lesson-format-title">Choose how you want it explained</h3></div><div className="format-tabs" role="tablist" aria-label="Explanation format">{([['watch','Watch'],['visual','See'],['read','Read']] as [LessonMode,string][]).map(([value,label])=><button type="button" role="tab" aria-selected={mode===value} className={mode===value?'on':''} key={value} onClick={()=>choose(value)}>{label}</button>)}</div></div>
  {mode==='watch'&&<div className="format-panel" role="tabpanel"><div className="lesson-player"><div className="player-top"><span className="code">VIDEO LESSON</span><span>{scene+1} / {steps.length}</span></div><div className="player-track" aria-hidden="true"><i style={{width:`${((scene+1)/Math.max(steps.length,1))*100}%`}}/></div>{active&&<article className="lesson-scene" key={active.id} aria-live="polite"><span className="scene-number">{String(scene+1).padStart(2,'0')}</span><div><h3>{active.title}</h3>{active.blocks.map((block,index)=><div key={index}><p>{block.text}</p><span className="cite">{block.citations.map(c=>c.page_or_section).join(', ')}</span></div>)}</div></article>}<div className="player-controls"><button className="btn" onClick={()=>setScene(value=>Math.max(0,value-1))} disabled={scene===0}>Previous</button><button className="btn primary" aria-pressed={playing} onClick={()=>setPlaying(value=>!value)}>{playing?'Pause':'Play lesson'}</button><button className="btn" onClick={()=>setScene(value=>Math.min(steps.length-1,value+1))} disabled={scene>=steps.length-1}>Next</button><button className="btn" onClick={restart}>Restart</button></div></div></div>}
  {mode==='visual'&&<div className="format-panel" role="tabpanel"><figure className="visual-recap"><svg viewBox="0 0 900 500" role="img" aria-labelledby="visual-title visual-desc"><title id="visual-title">Visual recap for {packet.title}</title><desc id="visual-desc">The missed topic connects to four source-grounded learning steps.</desc><path d="M450 250 L210 140 M450 250 L690 140 M450 250 L210 360 M450 250 L690 360" className="map-lines"/><rect x="315" y="195" width="270" height="110" rx="10" className="map-core"/><text x="450" y="242" textAnchor="middle" className="map-kicker">MISSED TOPIC</text><text x="450" y="273" textAnchor="middle" className="map-title">{packet.title.slice(0,34)}</text>{steps.slice(0,4).map((step,index)=>{const [x,y]=positions[index];return <g key={step.id}><rect x={x} y={y} width="300" height="120" rx="8" className="map-node"/><text x={x+22} y={y+34} className="map-number">{String(index+1).padStart(2,'0')}</text><text x={x+22} y={y+67} className="map-label">{step.title.slice(0,31)}</text><text x={x+22} y={y+94} className="map-source">{step.blocks[0]?.citations.map(c=>c.page_or_section).join(', ').slice(0,35)}</text></g>})}</svg><figcaption>Follow the four parts from reading the source to trying the practice.</figcaption></figure><ol className="visual-key">{steps.map((step,index)=><li key={step.id}><span>{String(index+1).padStart(2,'0')}</span><div><b>{step.title}</b><p>{step.blocks[0]?.text}</p></div></li>)}</ol></div>}
  {mode==='read'&&<div className="format-panel read-lesson" role="tabpanel"><p className="lesson-lede">Work through the explanation in order. Every section is tied to the material your teacher approved.</p>{steps.map((step,index)=><article className={'s-step'+(done.has(step.id)?' done':'')} key={step.id}><div className="step-head"><span className="ix">{String(index+1).padStart(2,'0')}</span><b>{step.title}</b><span className="spacer"/><button className={'btn'+(done.has(step.id)?' primary':'')} onClick={()=>complete(step.id)} disabled={done.has(step.id)}>{done.has(step.id)?'Completed ✓':'Mark complete'}</button></div>{step.blocks.map((block,blockIndex)=><div key={blockIndex}><blockquote>{block.text}</blockquote><span className="cite">{block.citations.map(c=>c.page_or_section).join(', ')}</span></div>)}</article>)}</div>}
  {mode!=='read'&&active&&<div className="format-complete"><p>Finished this part?</p><button className={'btn'+(done.has(active.id)?' primary':'')} onClick={()=>complete(active.id)} disabled={done.has(active.id)}>{done.has(active.id)?'Completed ✓':'Mark this part complete'}</button></div>}</section>
}
